name: GitHub Actions Demo
on: 
  push:
    branches:
      - "develop"
  pull_request:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with: 
          node-version: "16.x"
      - name: Building application
        run: |
          npm install
          npm install -g @angular/cli
          npm run build

  deploy_stg:
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    needs: build
    name: 'deploy stg'
    runs-on: ubuntu-latest
    steps:
      - run: echo 'deploy container'