name: GitHub Actions Demo
on: 
  # push:
  #   branches:
  #     - "develop"
  #     - "main"
  #     - "release/*"
  # pull_request:
  repository_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with: 
          node-version: "16.x"
      - name: Building application
        run: |
          npm install
          npm install -g @angular/cli
          npm run build

  # deploy_stg:
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
  #   needs: build
  #   name: 'deploy stg'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo 'deploy container'

  deploy_prod:
    name: 'deploy to production'
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: echo 'deploy container to prod'
      - run: echo ${{ github.event_name }}
      - run: echo ${{ github.event.event_type }}